import { AggregateRoot } from "../common/AggregateRoot";
import { OrderItem } from "./OrderItem";
import {
  OrderStatus,
  PaymentMethod,
  PaymentStatus,
} from "../constant/OrderEnums";
import { PhoneNumber } from "../value-objects/PhoneNumber";

export interface OrderProps {
  id?: string;
  userId: string;
  orderCode: string;
  status?: OrderStatus;
  totalAmount?: number;
  discountAmount?: number;
  shippingFee?: number;
  finalAmount?: number;
  paymentMethod: PaymentMethod;
  paymentStatus?: PaymentStatus;
  recipientName: string;
  phoneNumber: string;
  shippingAddress: string;
  shippingCode?: string | null;
  customerNote?: string | null;
  cancelReason?: string | null;
  items?: OrderItem[];
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date | null;
}

export class Order extends AggregateRoot {
  private _userId: string;
  private _orderCode: string;
  private _status: OrderStatus;
  private _totalAmount: number;
  private _discountAmount: number;
  private _shippingFee: number;
  private _finalAmount: number;
  private _paymentMethod: PaymentMethod;
  private _paymentStatus: PaymentStatus;
  private _recipientName: string;
  private _phoneNumber: PhoneNumber;
  private _shippingAddress: string;
  private _shippingCode: string | null;
  private _customerNote: string | null;
  private _cancelReason: string | null;
  private _items: OrderItem[];

  constructor(props: OrderProps) {
    super(props.id, props.createdAt, props.updatedAt, props.deletedAt);

    const phone = PhoneNumber.create(props.phoneNumber);
    if (!phone) {
      throw new Error("Số điện thoại nhận hàng không đúng định dạng Việt Nam.");
    }

    this._userId = props.userId;
    this._orderCode = props.orderCode;
    this._status = props.status ?? OrderStatus.PENDING;
    this._items = props.items || [];
    this._totalAmount =
      props.totalAmount ??
      this._items.reduce((sum, item) => sum + item.totalPrice, 0);
    this._discountAmount = props.discountAmount ?? 0;
    this._shippingFee = props.shippingFee ?? 0;
    this._finalAmount =
      props.finalAmount ??
      this._totalAmount - this._discountAmount + this._shippingFee;
    this._paymentMethod = props.paymentMethod;
    this._paymentStatus = props.paymentStatus ?? PaymentStatus.UNPAID;
    this._recipientName = props.recipientName;
    this._phoneNumber = phone;
    this._shippingAddress = props.shippingAddress;
    this._shippingCode = props.shippingCode ?? null;
    this._customerNote = props.customerNote ?? null;
    this._cancelReason = props.cancelReason ?? null;
  }

  public static generateOrderCode(): string {
    const timestamp = Date.now().toString(36).toUpperCase();
    const randomTail = crypto.randomUUID().split("-")[0].toUpperCase();
    return `ORD-${timestamp}-${randomTail}`;
  }

  /* khởi tạo đơn hàng mới */
  public static create(props: {
    userId: string;
    totalAmount?: number;
    discountAmount?: number;
    shippingFee?: number;
    paymentMethod: PaymentMethod;
    recipientName: string;
    phoneNumber: string;
    shippingAddress: string;
    customerNote?: string | null;
    items?: OrderItem[];
  }): Order {
    if (!props.userId || props.userId.trim().length === 0) {
      throw new Error("Mã người dùng (userId) không được để trống.");
    }

    if (!props.recipientName || props.recipientName.trim().length === 0) {
      throw new Error("Tên người nhận không được để trống.");
    }
    if (!props.phoneNumber || props.phoneNumber.trim().length === 0) {
      throw new Error("Số điện thoại nhận hàng không được để trống.");
    }
    if (!props.shippingAddress || props.shippingAddress.trim().length === 0) {
      throw new Error("Địa chỉ giao hàng không được để trống.");
    }

    const autoGeneratedCode = Order.generateOrderCode();

    return new Order({
      userId: props.userId,
      orderCode: autoGeneratedCode,
      status: OrderStatus.PENDING,
      totalAmount: props.totalAmount,
      discountAmount: props.discountAmount ?? 0,
      shippingFee: props.shippingFee ?? 0,
      paymentMethod: props.paymentMethod,
      paymentStatus: PaymentStatus.UNPAID,
      recipientName: props.recipientName,
      phoneNumber: props.phoneNumber,
      shippingAddress: props.shippingAddress,
      customerNote: props.customerNote,
      items: props.items || [],
    });
  }

  // Getters
  public get userId(): string {
    return this._userId;
  }
  public get orderCode(): string {
    return this._orderCode;
  }
  public get status(): OrderStatus {
    return this._status;
  }
  public get totalAmount(): number {
    return this._totalAmount;
  }
  public get discountAmount(): number {
    return this._discountAmount;
  }
  public get shippingFee(): number {
    return this._shippingFee;
  }
  public get finalAmount(): number {
    return this._finalAmount;
  }
  public get paymentMethod(): PaymentMethod {
    return this._paymentMethod;
  }
  public get paymentStatus(): PaymentStatus {
    return this._paymentStatus;
  }
  public get recipientName(): string {
    return this._recipientName;
  }
  public get phoneNumber(): string {
    return this._phoneNumber.value;
  }
  public get shippingAddress(): string {
    return this._shippingAddress;
  }
  public get shippingCode(): string | null {
    return this._shippingCode;
  }
  public get customerNote(): string | null {
    return this._customerNote;
  }
  public get cancelReason(): string | null {
    return this._cancelReason;
  }
  public get items(): ReadonlyArray<OrderItem> {
    return this._items;
  }

  // Thêm sản phẩm vào đơn hàng
  public addItem(productId: string, quantity: number, unitPrice: number): void {
    const item = OrderItem.create({
      orderId: this.id,
      productId,
      quantity,
      unitPrice,
    });
    this._items.push(item);
    this._totalAmount += item.totalPrice;
    this.recalculateFinalAmount();
  }
  public confirm(): void {
    if (this._status !== OrderStatus.PENDING) {
      throw new Error(
        "Chỉ có thể xác nhận đơn hàng khi đơn đang ở trạng thái Chờ xử lý.",
      );
    }
    this._status = OrderStatus.PROCESSING;
    this.touch();
  }
  //Bàn giao cho đơn vị vận chuyển
  public ship(shippingCode?: string): void {
    if (this._status !== OrderStatus.PROCESSING) {
      throw new Error(
        "Đơn hàng phải được đóng gói xong mới có thể bàn giao vận chuyển.",
      );
    }
    this._status = OrderStatus.SHIPPED;
    if (shippingCode && shippingCode.trim().length > 0) {
      this._shippingCode = shippingCode.trim();
    }
    this.touch();
  }
  //Khách hàng đã nhận hàng thành công
  public markAsDelivered(): void {
    if (this._status !== OrderStatus.SHIPPED) {
      throw new Error(
        "Đơn hàng chưa được giao đi thì không thể đánh dấu Đã giao thành công.",
      );
    }
    this._status = OrderStatus.DELIVERED;
    // Nếu là đơn ship COD, nhận hàng xong đồng nghĩa với việc đã thanh toán
    if (this._paymentMethod === PaymentMethod.COD) {
      this._paymentStatus = PaymentStatus.PAID;
    }
    this.touch();
  }
  /** Hủy đơn hàng */
  public cancel(reason: string): void {
    if (
      this._status === OrderStatus.SHIPPED ||
      this._status === OrderStatus.DELIVERED
    ) {
      throw new Error(
        "Không thể hủy đơn hàng khi đã giao cho đơn vị vận chuyển.",
      );
    }
    this._status = OrderStatus.CANCELLED;
    this._cancelReason = reason;
    this.touch();
  }

  //Đánh dấu thanh toán thành công
  public markAsPaid(): void {
    if (this._paymentStatus === PaymentStatus.PAID) {
      return; // Đã thanh toán rồi thì không làm gì thêm
    }
    this._paymentStatus = PaymentStatus.PAID;
    // Nếu đơn đang chờ thanh toán online -> Chuyển sang Đang xử lý
    if (this._status === OrderStatus.PENDING) {
      this._status = OrderStatus.PROCESSING;
    }
    this.touch();
  }
  // Cho phép khách hàng đổi địa chỉ nhận hàng nếu đơn chưa giao
  public updateShippingInfo(
    recipientName: string,
    phoneNumber: string,
    address: string,
  ): void {
    if (
      this._status === OrderStatus.SHIPPED ||
      this._status === OrderStatus.DELIVERED
    ) {
      throw new Error(
        "Không thể thay đổi địa chỉ khi đơn hàng đang được giao.",
      );
    }
    if (this._status === OrderStatus.CANCELLED) {
      throw new Error("Đơn hàng đã hủy không thể sửa thông tin.");
    }

    const phone = PhoneNumber.create(phoneNumber);
    if (!phone) {
      throw new Error("Số điện thoại nhận hàng không đúng định dạng Việt Nam.");
    }

    this._recipientName = recipientName;
    this._phoneNumber = phone;
    this._shippingAddress = address;
    this.touch();
  }
  // Áp dụng mã Voucher giảm giá
  public applyDiscount(discountAmount: number): void {
    if (discountAmount < 0) {
      throw new Error("Số tiền giảm giá không được âm.");
    }
    this._discountAmount = discountAmount;
    this.recalculateFinalAmount();
  }
  //hàm tự động tính lại tổng tiền thanh toán cuối cùng
  private recalculateFinalAmount(): void {
    const calculated =
      this._totalAmount - this._discountAmount + this._shippingFee;
    this._finalAmount = calculated > 0 ? calculated : 0;
    this.touch();
  }
}
